// Generated by CoffeeScript 1.8.0
(function() {
  var Formbuilder;

  Formbuilder = window.Formbuilder;

  describe('Formbuilder', function() {
    beforeEach(function() {
      return this.view = new Formbuilder();
    });
    return it('should exist', function() {
      return expect(this.view).to.be.ok;
    });
  });

}).call(this);
