// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = function(config) {
    return config.set({
      basePath: '../',
      files: ['vendor/js/vendor.js', 'dist/formbuilder-min.js', 'test/vendor/js/chai.js', 'test/vendor/js/sinon.js', 'test/vendor/js/chai-jquery.js', 'test/vendor/js/chai-changes.js', 'test/vendor/js/chai-backbone.js', 'test/vendor/js/sinon-chai.js', 'test/helpers.coffee', 'test/**/*_test.coffee'],
      port: 8080,
      runnerPort: 9100,
      colors: true,
      logLevel: config.LOG_INFO,
      autoWatch: false,
      browsers: ['PhantomJS'],
      preprocessors: {
        '**/*.coffee': 'coffee'
      },
      frameworks: ['mocha'],
      plugins: ['karma-mocha', 'karma-coffee-preprocessor', 'karma-phantomjs-launcher', 'karma-chrome-launcher', 'karma-firefox-launcher', 'karma-safari-launcher']
    });
  };

}).call(this);
